### ISSUE TITLE
Could you add a strong name?

### ISSUE THREAD

**Issue by realvizu** [dbolin/Apex.Analyzers#11]
Hi, thanks for this handy tool!

Could you add strong name to both Apex.Analyzers.Immutable and Apex.Analyzers.Immutable.Attributes?
My project is strong named so I get CS8002 error when I try to use your assemblies.

> error CS8002: Referenced assembly 'Apex.Analyzers.Immutable.Attributes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.

**Comment by dbolin** [comment]
Done - nuget packages should be available shortly as well.  I never did strong naming before because back when I read about it (probably about 10 years ago) it wasn't really encouraged.

I'll be doing this for the rest of my public libraries soon.
