### ISSUE TITLE
Whitelist is hard-coded

### ISSUE THREAD

**Issue by mwelsh1118** [dbolin/Apex.Analyzers#31]
Could the list of whitelisted types be configurable? Similar to Microsoft's [BannedApiAnalyzer](https://github.com/DotNetAnalyzers/BannedApiAnalyzer), there could be an additional file added to the analyzed project that could extend the list of white-listed types. Happy to implement this. Just don't want to go down this road unless it's likely to be accepted.

**Comment by dbolin** [comment]
Sure - I just haven't done anything with consumer configurable analyzers, so I don't know what the best practice is there.  Is a text file like BannedSymbols.txt still considered a good way to do this?  Are there alternatives?

If you want you can answer these or I'll do some research when I have the time.

**Comment by mwelsh1118** [comment]
I can't say definitively what the best practice would be, but that is the approach taken by the dotnet team. The [original link](https://github.com/DotNetAnalyzers/BannedApiAnalyzer) was to a precursor project that's been archived, but here's a link to the [current project](https://github.com/dotnet/roslyn-analyzers#microsoftcodeanalysisbannedapianalyzers).

**Comment by dbolin** [comment]
Closed by #32
