### ISSUE TITLE
C# 9 Init-only property setters trigger IMM002

### ISSUE THREAD

**Issue by mwelsh1118** [dbolin/Apex.Analyzers#57]
The following auto-property will trigger IMM002, even though the property is immutable after the object is initialized:

```
public int Property { get; init; }
```
I can look at creating a Pull Request to address this if you'd like.

**Comment by dbolin** [comment]
This is fixed in version 1.2.6, and adds another analyzer to catch 'this' reference escaping in the body of an init only property method.

**Comment by mwelsh1118** [comment]
Confirmed. Thanks for the quick turnaround!
